# Cargo.toml
[package]
name = "pcw_protocol"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Peer Cash Wallet Protocol (PCW-1): IP-to-IP BSV settlement protocol per spec."
repository = "https://github.com/murphsicles/PCW-1"
readme = "README.md"

[dependencies]
sv = { git = "https://github.com/murphsicles/rust-sv", branch = "master" }
tokio = { version = "1.40", features = ["time", "rt-multi-thread"] }
secp256k1 = { version = "0.31", features = ["recovery"] }
sha2 = "0.10"
ripemd = "0.1"
base58 = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hmac = "0.12"
merlin = "3.0"
chrono = "0.4"
thiserror = "2.0"
unicode-normalization = "0.1"

[dev-dependencies]
proptest = "1.7"
criterion = "0.6"

[profile.dev]
opt-level = 3
