edition = "2024"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
