# rustfmt.toml
edition = "2024"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Block"
format_strings = true
format_code_in_doc_comments = true
comment_width = 100
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
